"""add_artifact_tables

Revision ID: 5c10a2a62477
Revises: 
Create Date: 2025-12-19 17:55:01.519618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c10a2a62477'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_stats_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genre_id', 'date', name='uq_genre_stats_daily')
    )
    op.create_index(op.f('ix_genre_stats_daily_date'), 'genre_stats_daily', ['date'], unique=False)
    op.create_index(op.f('ix_genre_stats_daily_genre_id'), 'genre_stats_daily', ['genre_id'], unique=False)
    op.create_index(op.f('ix_genre_stats_daily_id'), 'genre_stats_daily', ['id'], unique=False)
    op.create_table('ratings_by_decade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decade', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('movie_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_by_decade_decade'), 'ratings_by_decade', ['decade'], unique=True)
    op.create_index(op.f('ix_ratings_by_decade_id'), 'ratings_by_decade', ['id'], unique=False)
    op.create_table('movie_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('recommendations_json', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_recommendations_generated_at'), 'movie_recommendations', ['generated_at'], unique=False)
    op.create_index(op.f('ix_movie_recommendations_id'), 'movie_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_movie_recommendations_movie_id'), 'movie_recommendations', ['movie_id'], unique=False)
    op.create_table('movie_trending_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'date', name='uq_movie_trending_daily')
    )
    op.create_index(op.f('ix_movie_trending_daily_date'), 'movie_trending_daily', ['date'], unique=False)
    op.create_index(op.f('ix_movie_trending_daily_id'), 'movie_trending_daily', ['id'], unique=False)
    op.create_index(op.f('ix_movie_trending_daily_movie_id'), 'movie_trending_daily', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_trending_daily_movie_id'), table_name='movie_trending_daily')
    op.drop_index(op.f('ix_movie_trending_daily_id'), table_name='movie_trending_daily')
    op.drop_index(op.f('ix_movie_trending_daily_date'), table_name='movie_trending_daily')
    op.drop_table('movie_trending_daily')
    op.drop_index(op.f('ix_movie_recommendations_movie_id'), table_name='movie_recommendations')
    op.drop_index(op.f('ix_movie_recommendations_id'), table_name='movie_recommendations')
    op.drop_index(op.f('ix_movie_recommendations_generated_at'), table_name='movie_recommendations')
    op.drop_table('movie_recommendations')
    op.drop_index(op.f('ix_ratings_by_decade_id'), table_name='ratings_by_decade')
    op.drop_index(op.f('ix_ratings_by_decade_decade'), table_name='ratings_by_decade')
    op.drop_table('ratings_by_decade')
    op.drop_index(op.f('ix_genre_stats_daily_id'), table_name='genre_stats_daily')
    op.drop_index(op.f('ix_genre_stats_daily_genre_id'), table_name='genre_stats_daily')
    op.drop_index(op.f('ix_genre_stats_daily_date'), table_name='genre_stats_daily')
    op.drop_table('genre_stats_daily')
    # ### end Alembic commands ###
